import numpy as np

PER_WING_MODEL = 'PER_WING_MODEL'
ALL_POINTS_MODEL = 'ALL_POINTS_MODEL'
TRAIN_ON_3_GOOD_CAMERAS_MODEL = "TRAIN_ON_3_GOOD_CAMERAS_MODEL"
MODEL_18_POINTS_PER_WING = "MODEL_18_POINTS_PER_WING"
MODEL_18_POINTS_3_GOOD_CAMERAS = "MODEL_18_POINTS_3_GOOD_CAMERAS"
MODEL_18_POINTS_PER_WING_VIT = "MODEL_18_POINTS_PER_WING_VIT"
ALL_CAMS_DISENTANGLED_PER_WING_VIT = "ALL_CAMS_DISENTANGLED_PER_WING_VIT"
ALL_CAMS_DISENTANGLED_PER_WING_CNN = "ALL_CAMS_DISENTANGLED_PER_WING_CNN"
PRETRAINED_LEAP = "PRETRAINED_LEAP"
GPTNET = "GPTNET"
ALL_POINTS_MODEL_VIT = 'ALL_POINTS_MODEL_VIT'
ALL_CAMS = "ALL_CAMS"
ALL_CAMS_18_POINTS = "ALL_CAMS_18_POINTS"
ALL_CAMS_18_POINTS_VIT = "ALL_CAMS_18_POINTS_VIT"
MEAN_SQUARE_ERROR = "MEAN_SQUARE_ERROR"
MOVIE_TRAIN_SET = "MOVIE_TRAIN_SET"
RANDOM_TRAIN_SET = "RANDOM_TRAIN_SET"
LEFT_INDEXES = np.arange(0, 7)
RIGHT_INDEXES = np.arange(7, 14)
